baseURL = 'https://amemiya02.github.io'
languageCode = 'zh-CN'
title = '个人技术博客'
theme = "FixIt"

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'],['$', '$']]

[params]
  env = "production"

  # FixIt 全局页面配置
  [params.page.toc]
    enable = true
  [params.page.code]
    copy = true
  [params.page.math]
    enable = true

  # FixIt 的个人主页模式配置 (替换掉你的 params.profileMode)
  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "avatar.jpg"
      title = "Amemiya"
      subtitle = "欢迎来的我的个人博客"
      # FixIt 中主页的社交图标配置
      [params.home.profile.social]
        github = "https://github.com/amemiya02"

  # FixIt 顶部导航栏配置 (通常在菜单中配置，这里供参考)
  [params.header]
    # 你的按钮可以放到这里或者 config 的 [menu.main] 中